# Generated by Django 3.1.7 on 2021-02-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210222_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('carbon_price_per_meal', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Low Carbon Emission', 'Low Carbon Emission'), ('High Carbon Emission', 'High Carbon Emission')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_offset', models.BooleanField(blank=True, default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('diet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.diet')),
            ],
        ),
    ]
